### ISSUE TITLE
Set up custom SMTP send command

### ISSUE THREAD

**Issue by soywod** [pimalaya/himalaya#351]
https://github.com/soywod/himalaya/discussions/177#discussioncomment-2298474

**Comment by jarkkojs** [comment]
For reference, this is how it works in Evolution: https://www.dropbox.com/s/r151wkp33y7480w/Screenshot%20from%202022-03-21%2006-19-42.png?dl=0

**Comment by jarkkojs** [comment]
@soywod I've kind of started working on this, so here's what I've planned.

Git has chosen the approach of having a single option:

```
[sendemail]
	smtpserver = /usr/bin/msmtp
```

On the other hand, mutt has a separate option:

```
set sendmail = "/usr/bin/msmtp"
```

The upside of Git approach is less ambiguity in semantics because both SMTP server and a send command cannot exist in the same configuration file. The downside is more ambiguity in the mean and purpose of the configuration option.

I'm leaning towards adding a new option `smtp-host-cmd` and sane defaults: if the configuration option exists for an account, it overrides `smtp-host` if they co-exists. Or should it be an error condition?

**Comment by soywod** [comment]
> smtpserver = /usr/bin/msmtp

I just understood what you mean. The fact to use a path to an executable at the place of the `smtp-server` config. I'm not so fan because this will will to some messy conditional stuff in the config parsing. I would like to keep it really simple and to let `serde` do the job as much as possible. I still highly consider the explicit way with an adjacently-tagged enum.

**Comment by jarkkojs** [comment]
Yeah, I think the "mutt alike" thing is cleaner in the end. Most people can ignore it, and those who need it, will add it. You don't put it in your config by accident.

**Comment by jarkkojs** [comment]
I'll prepare some sort of PR for that approach.

**Comment by jarkkojs** [comment]
> > @soywod I've kind of started working on this
> 
> First of all, thanks for considering helping the project! I invite you to read the [contributing guide](https://github.com/soywod/himalaya/blob/master/CONTRIBUTING.md). I just 

Yeah, I mean I just found about this. It kind of complements my mutt workflow (I'm a kernel maintainer so a great email workflow matters to me a lot), rather than replaces mutt :-) This kind of command-line interface is perfect when you're working on e.g. a patch set, but do not want to do a full context switch to email but still want to have full access to it. Thank you for making such a great program!

**Comment by jarkkojs** [comment]
I was thinking something along the lines of this.

SMTP:

```toml
sender-type = "smtp" # default
```

Sendmail:

```toml
sender-type = "sendmail"
sendmail-command = "/usr/bin/msmtp"
```

The 2nd is any command that is (semi)compatible with the command-line of the original sendmail program.

**Comment by soywod** [comment]
I understand your point. I was stuck to the fact that no matter if we use the Rust SMTP client or a script, it is still a SMTP client. Then `sender-type` makes sense.

To be in phase with https://github.com/soywod/himalaya/issues/344, I suggest the following:

```toml
# everything related to sending emails goes here,
# in contrast of having everything at the root level
# starting by `smtp-*`
[outgoing]
type = "smtp"
host =
port =
starttls =
insecure =
login =
passwd-cmd =

# does it make sense to have multiple
# types, one per tool (to maximize the compatibility)?
[outgoing]
type = "sendmail"
bin = "/usr/bin/sendmail"

[outgoing]
type = "msmtp"
bin = "/usr/bin/msmtp"

[outgoing]
type = "mailx"
bin = "/usr/bin/mailx"

# ...
```

**Comment by jarkkojs** [comment]
The layout you proposed makes sense but I would add just sendmail type for now. It has worked for Git, mutt and Evolution for years and people use msmtp, mailx, ssmtp, postfix etc. as a drop-in replacement for it. So as long as the structure is extensible I would focus solely on sendmail and consider anything else on request.

**Comment by jarkkojs** [comment]
Maximizing compatibility should happen on-need basis but it is of course important to make design that allows to do it on need :-)

**Comment by jarkkojs** [comment]
Thanks, from that example I anyway fully understood how and why you would prefer adjacently-tagged enum :-) Makes a lot of sense.

**Comment by soywod** [comment]
> The layout you proposed makes sense but I would add just sendmail type for now.

Alright, let's go for it! Thanks for your precious help. Let me know if you need help implementing this.

Just for info, the `development` branch is a bit "messed up" because of https://github.com/soywod/himalaya/issues/340. For now I just moved everything in a cargo `cli` workspace, but stuff need to be extracted into the `lib` workspace. Maybe it could be a good occasion for you to develop it directly inside the `lib` workspace to limit future conflicts!

**Comment by soywod** [comment]
Added in the last release [`v0.6.1`](https://github.com/soywod/himalaya/releases/tag/v0.6.1) :tada: you can set up the command using the `sendmail` sender:

```toml
sender = "sendmail"
sendmail-cmd = "your-command" # for eg. /usr/bin/msmtp
```
