### ISSUE TITLE
Folder aliases broken with the Maildir backend

### ISSUE THREAD

**Issue by soywod** [pimalaya/himalaya#526]
### Discussed in https://github.com/pimalaya/himalaya/discussions/519

<div type='discussions-op-text'>

<sup>Originally posted by **grimnight** December 10, 2024</sup>
I just installed Himalaya to try it out. I have been trying to use folder aliases, but I can't get them to work. Am I doing something wrong or have I misunderstood folder aliases?

Excerpt from my config (sanitized):
```toml
[accounts.account_name]
default = true
email = "grimnight@email"

display-name = "GrimNight"
backend.type = "maildir"
backend.root-dir = "~/.local/share/mail/grimnight/"
backend.maildirpp = false
message.send.backend.type = "sendmail"
message.send.backend.cmd = "/usr/sbin/sendmail"

folder.alias.inbox = "INBOX"
folder.alias.old = "Archives"
```

And my attempts:
```shell
~
❯ himalaya envelope list -f old
Error:
   0: cannot find maildir matching name old

Note: Run with --debug to enable logs with spantrace.
Note: Run with --trace to enable verbose logs with backtrace.

~
❯ himalaya envelope list -f inbox
Error:
   0: cannot find maildir matching name inbox

Note: Run with --debug to enable logs with spantrace.
Note: Run with --trace to enable verbose logs with backtrace.
```

The folder aliases don't seem to work, unless I have misunderstood them.

Both `himalaya envelope list` and `himalaya envelope list -f INBOX` work fine.
</div>

**Comment by kiil** [comment]
I am not even using maildir and have the same issue with aliases.

**Comment by soywod** [comment]
Good news: it was a mistake in the documentation. It should be `aliases` instead of `alias`:

```toml
folder.aliases.inbox = "INBOX"
folder.aliases.old = "Archives"
```
